cc_library(
    name = "system",
    srcs = [
        "posix.cpp",
        "filesystem.cpp",
    ],
    hdrs = [
        "system.h", 
        "util.h"
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//lib/error:error",
    ],
)